<html>
<head>
<title>TestNG:  All tests</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>All tests</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>9/1/2</td>
</tr><tr>
<td>Started on:</td><td>Fri May 01 20:17:04 PDT 2020</td>
</tr>
<tr><td>Total time:</td><td>60 seconds (60886 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='tests.LoginTests.test_Fails()'><b>test_Fails</b><br>Test class: tests.LoginTests</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at tests.LoginTests.test_Fails(LoginTests.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace743019168", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace743019168'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.failNotEquals(Assert.java:969)
	at org.testng.Assert.assertTrue(Assert.java:43)
	at org.testng.Assert.assertTrue(Assert.java:53)
	at tests.LoginTests.test_Fails(LoginTests.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
</pre></div></td>
<td>0</td>
<td>tests.LoginTests@6dde5c8c</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='tests.HomepageTests.addSongToPlaylist_byMenuButton_CreatePLaylist_thenAddSong()'><b>addSongToPlaylist_byMenuButton_CreatePLaylist_thenAddSong</b><br>Test class: tests.HomepageTests<br>Parameters: testpro.user02@testpro.io, te$t$tudent02, Lesser Faith, zebra4</td>
<td></td>
<td>3</td>
<td>tests.HomepageTests@fe18270</td></tr>
<tr>
<td title='tests.LoginTests.loginTest_correctCredentials_loggedToApp()'><b>loginTest_correctCredentials_loggedToApp</b><br>Test class: tests.LoginTests<br>Parameters: testpro.user02@testpro.io, te$t$tudent02</td>
<td></td>
<td>2</td>
<td>tests.LoginTests@6dde5c8c</td></tr>
<tr>
<td title='tests.HomepageTests.loginTest_createNewPlaylist_newPlaylistCreated()'><b>loginTest_createNewPlaylist_newPlaylistCreated</b><br>Test class: tests.HomepageTests<br>Parameters: testpro.user02@testpro.io, te$t$tudent02, zebra4</td>
<td></td>
<td>5</td>
<td>tests.HomepageTests@fe18270</td></tr>
<tr>
<td title='tests.LoginTests.loginTest_incorrectCredentials_notLoggedToApp()'><b>loginTest_incorrectCredentials_notLoggedToApp</b><br>Test class: tests.LoginTests<br>Parameters: testpro.user02@testpro.io, *******</td>
<td></td>
<td>1</td>
<td>tests.LoginTests@6dde5c8c</td></tr>
<tr>
<td title='tests.LoginTests_new.new_loginTest_correctCredentials_loggedToApp()'><b>new_loginTest_correctCredentials_loggedToApp</b><br>Test class: tests.LoginTests_new</td>
<td></td>
<td>3</td>
<td>tests.LoginTests_new@5123a213</td></tr>
<tr>
<td title='tests.HomepageTests_new.new_loginTest_createNewPlaylist_newPlaylistCreated()'><b>new_loginTest_createNewPlaylist_newPlaylistCreated</b><br>Test class: tests.HomepageTests_new</td>
<td></td>
<td>5</td>
<td>tests.HomepageTests_new@6fb0d3ed</td></tr>
<tr>
<td title='tests.LoginTests_new.new_loginTest_incorrectCredentials_notLoggedToApp()'><b>new_loginTest_incorrectCredentials_notLoggedToApp</b><br>Test class: tests.LoginTests_new</td>
<td></td>
<td>1</td>
<td>tests.LoginTests_new@5123a213</td></tr>
<tr>
<td title='tests.HomepageTests_new.new_scrollDown()'><b>new_scrollDown</b><br>Test class: tests.HomepageTests_new</td>
<td></td>
<td>3</td>
<td>tests.HomepageTests_new@6fb0d3ed</td></tr>
<tr>
<td title='tests.HomepageTests.scrollDown()'><b>scrollDown</b><br>Test class: tests.HomepageTests<br>Parameters: testpro.user02@testpro.io, te$t$tudent02, zebra4, newZebra4</td>
<td></td>
<td>3</td>
<td>tests.HomepageTests@fe18270</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='tests.LoginTests.test_Fails()'><b>test_Fails</b><br>Test class: tests.LoginTests</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at tests.LoginTests.test_Fails(LoginTests.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace844784659", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace844784659'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.failNotEquals(Assert.java:969)
	at org.testng.Assert.assertTrue(Assert.java:43)
	at org.testng.Assert.assertTrue(Assert.java:53)
	at tests.LoginTests.test_Fails(LoginTests.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
</pre></div></td>
<td>0</td>
<td>tests.LoginTests@6dde5c8c</td></tr>
<tr>
<td title='tests.LoginTests.test_Fails()'><b>test_Fails</b><br>Test class: tests.LoginTests</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at tests.LoginTests.test_Fails(LoginTests.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace842506989", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace842506989'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.failNotEquals(Assert.java:969)
	at org.testng.Assert.assertTrue(Assert.java:43)
	at org.testng.Assert.assertTrue(Assert.java:53)
	at tests.LoginTests.test_Fails(LoginTests.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
</pre></div></td>
<td>0</td>
<td>tests.LoginTests@6dde5c8c</td></tr>
</table><p>
</body>
</html>